package jp.ddd.server.adapter.gateway.dynamodb.table;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Map;

/**
 * Created by noguchi_kohei 
 */
@NoArgsConstructor
@Data
@DynamoDBTable(tableName = "message")
public class MessageDyn implements Serializable {
    private static final long serialVersionUID = 1L;

    @DynamoDBHashKey(attributeName = "message_id")
    @DynamoDBAutoGeneratedKey
    private String messageId;
    @DynamoDBAttribute(attributeName = "room_id")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "idx_rid_mat")
    private String roomId;
    @DynamoDBAttribute(attributeName = "message_at")
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "idx_rid_mat")
    private String messageAt;
    @DynamoDBAttribute(attributeName = "user_id")
    private String userId;
    private String content;
    @DynamoDBAttribute(attributeName = "last_edit_at")
    private String lastEditAt;
    @DynamoDBAttribute(attributeName = "user_read_map")
    private Map<String, Boolean> userReadMap;
}
