package jp.ddd.server.adapter.gateway.dynamodb.table;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * Created by noguchi_kohei 
 */
@NoArgsConstructor
@Data
@DynamoDBTable(tableName = "room")
public class RoomDyn implements Serializable {
    private static final long serialVersionUID = 1L;
    @DynamoDBHashKey(attributeName = "room_id")
    @DynamoDBAutoGeneratedKey
    private String roomId;
    @DynamoDBAttribute(attributeName = "create_user_id")
    private String createUserId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute(attributeName = "last_message_at")
    private String lastMessageAt;
}
