package jp.ddd.server.adapter.gateway.dynamodb.table;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * Created by noguchi_kohei 
 */
//@Builder
//@NoArgsConstructor
//@AllArgsConstructor
//@Data
//@DynamoDBTable(tableName = "ds_user")
public class UserDyn implements Serializable {
    private static final long serialVersionUID = 1L;

//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
//    private Integer userId;
//
//    @DynamoDBAttribute
//    @DynamoDBIndexHashKey(globalSecondaryIndexName = "idx_lid")
//    private String loginId;
//
//    @DynamoDBAttribute
//    private String pass;
//
//    @DynamoDBAttribute
//    private String name;
//
//    @DynamoDBAttribute
//    private String email;
//
//    @DynamoDBAttribute
//    private String tel;

}
